# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I protobuff protobuff/sso/sso.proto --go_out=./gen/gogen --go_opt=paths=source_relative --go-grpc_out=./gen/gogen/ --go-grpc_opt=paths=source_relative